import { Player } from "./interfaces";

export const rawPlayersData: Player[] = [
  {
    name: "Xande",
    rating: 1,
    matches: [
      { g: 0, a: 0 },
      { g: 0, a: 0 },
      { g: 2, a: 0 },
      { g: 0, a: 0 },
      { g: 0, a: 0 },
      { g: 2, a: 0 },
    ],
  },
  {
    name: "Bersi",
    rating: 1,
    matches: [
      { g: 0, a: 0 },
      { g: 0, a: 0 },
      { g: 1, a: 0 },
      { g: 0, a: 0 },
      { g: 1, a: 1 },
      { g: 1, a: 0 },
    ],
  },
  {
    name: "Daniboy",
    rating: 3,
    matches: [
      { g: 2, a: 1 },
      { g: 1, a: 1 },
      { g: 1, a: 0 },
      { g: 2, a: 1 },
      { g: 3, a: 1 },
      { g: 2, a: 1 },
    ],
  },
  {
    name: "Denes",
    rating: 3,
    matches: [
      { g: 1, a: 1 },
      { g: 1, a: 1 },
      { g: 3, a: 1 },
      { g: 1, a: 1 },
      { g: 2, a: 0 },
      { g: 0, a: 0 },
    ],
  },
  {
    name: "Godoy",
    rating: 1,
    matches: [
      { g: 1, a: 0 },
      { g: 0, a: 0 },
      { g: 0, a: 0 },
      { g: "-", a: "-" },
      { g: "-", a: "-" },
      { g: "-", a: "-" },
    ],
  },
  {
    name: "Luan",
    rating: 4,
    matches: [
      { g: 0, a: 1 },
      { g: 0, a: 0 },
      { g: 2, a: 2 },
      { g: 2, a: 3 },
      { g: 0, a: 2 },
      { g: 1, a: 1 },
    ],
  },
  {
    name: "Peace",
    rating: 2,
    matches: [
      { g: 0, a: 0 },
      { g: 0, a: 0 },
      { g: 1, a: 0 },
      { g: 0, a: 0 },
      { g: "-", a: "-" },
      { g: "-", a: "-" },
    ],
  },
  {
    name: "Kim",
    rating: 3,
    matches: [
      { g: 1, a: 0 },
      { g: 3, a: 0 },
      { g: 1, a: 3 },
      { g: 1, a: 0 },
      { g: 3, a: 1 },
      { g: 1, a: 1 },
    ],
  },
  {
    name: "Mafes",
    rating: 2,
    matches: [
      { g: 0, a: 0 },
      { g: 0, a: 0 },
      { g: "-", a: "-" },
      { g: 0, a: 0 },
      { g: 0, a: 0 },
      { g: 0, a: 2 },
    ],
  },
  {
    name: "Mencalha",
    rating: 5,
    matches: [
      { g: 5, a: 2 },
      { g: 4, a: 3 },
      { g: 3, a: 3 },
      { g: 0, a: 3 },
      { g: 2, a: 1 },
      { g: 3, a: 7 },
    ],
  },
  {
    name: "Prestes",
    rating: 2,
    matches: [
      { g: 0, a: 1 },
      { g: 1, a: 1 },
      { g: 1, a: 0 },
      { g: 0, a: 0 },
      { g: "-", a: "-" },
      { g: 1, a: 0 },
    ],
  },
  {
    name: "Pedro",
    rating: 3,
    matches: [
      { g: 1, a: 1 },
      { g: 0, a: 0 },
      { g: 2, a: 1 },
      { g: 2, a: 2 },
      { g: 2, a: 1 },
      { g: 1, a: 1 },
    ],
  },
  {
    name: "Siqueira",
    rating: 4,
    matches: [
      { g: 0, a: 0 },
      { g: "-", a: "-" },
      { g: 1, a: 0 },
      { g: 0, a: 1 },
      { g: 0, a: 0 },
      { g: 1, a: 0 },
    ],
  },
  {
    name: "Diniz",
    rating: 5,
    matches: [
      { g: 0, a: 0 },
      { g: 4, a: 1 },
      { g: 3, a: 3 },
      { g: 1, a: 1 },
      { g: "-", a: "-" },
      { g: 3, a: 1 },
    ],
  },
  {
    name: "Rafael",
    rating: 5,
    matches: [
      { g: 0, a: 0 },
      { g: 0, a: 0 },
      { g: "-", a: "-" },
      { g: 6, a: 2 },
      { g: 4, a: 0 },
      { g: 5, a: 4 },
    ],
  },
  {
    name: "SAJ",
    rating: 1,
    matches: [
      { g: 0, a: 0 },
      { g: "-", a: "-" },
      { g: "-", a: "-" },
      { g: 0, a: 0 },
      { g: "-", a: "-" },
      { g: "-", a: "-" },
    ],
  },
  {
    name: "Vinibala",
    rating: 4,
    matches: [
      { g: 1, a: 0 },
      { g: 0, a: 1 },
      { g: 0, a: 1 },
      { g: 0, a: 0 },
      { g: "-", a: "-" },
      { g: "-", a: "-" },
    ],
  },
  {
    name: "Vinigod",
    rating: 5,
    matches: [
      { g: 2, a: 0 },
      { g: 1, a: 0 },
      { g: 0, a: 2 },
      { g: 0, a: 2 },
      { g: "-", a: "-" },
      { g: 4, a: 1 },
    ],
  },
  {
    name: "Hugo",
    rating: 2,
    matches: [
      { g: 0, a: 0 },
      { g: 0, a: 1 },
      { g: 0, a: 0 },
      { g: 0, a: 1 },
      { g: 0, a: 0 },
      { g: 0, a: 0 },
    ],
  },
  {
    name: "Peixoto",
    rating: 1,
    matches: [
      { g: 0, a: 0 },
      { g: 0, a: 0 },
      { g: 1, a: 1 },
      { g: 1, a: 1 },
      { g: 0, a: 0 },
      { g: 1, a: 0 },
    ],
  },
  {
    name: "Theodoro",
    rating: 2,
    matches: [
      { g: 0, a: 0 },
      { g: 0, a: 0 },
      { g: 0, a: 0 },
      { g: 0, a: 0 },
      { g: "-", a: "-" },
      { g: "-", a: "-" },
    ],
  },
  {
    name: "Danilo (Pxt)",
    rating: 4,
    matches: [
      { g: 3, a: 0 },
      { g: 0, a: 0 },
      { g: 2, a: 1 },
      { g: "-", a: "-" },
      { g: 1, a: 4 },
      { g: 4, a: 2 },
    ],
  },
  {
    name: "Daniel (Pxt)",
    rating: 3,
    matches: [
      { g: 0, a: 0 },
      { g: 0, a: 0 },
      { g: 1, a: 0 },
      { g: "-", a: "-" },
      { g: "-", a: "-" },
      { g: "-", a: "-" },
    ],
  },
  {
    name: "Jonas (Pxt)",
    rating: 3,
    matches: [
      { g: 0, a: 0 },
      { g: 0, a: 0 },
      { g: "-", a: "-" },
      { g: "-", a: "-" },
      { g: "-", a: "-" },
      { g: "-", a: "-" },
    ],
  },
  {
    name: "Guilherme (Mencalha)",
    rating: 3,
    matches: [
      { g: 0, a: 0 },
      { g: 0, a: 0 },
      { g: 0, a: 0 },
      { g: 0, a: 0 },
      { g: "-", a: "-" },
      { g: "-", a: "-" },
    ],
  },
  {
    name: "Douglas (Mencalha)",
    rating: 3,
    matches: [
      { g: 0, a: 0 },
      { g: 0, a: 0 },
      { g: 0, a: 0 },
      { g: 0, a: 0 },
      { g: "-", a: "-" },
      { g: "-", a: "-" },
    ],
  },
  {
    name: "Heitor (Mencalha)",
    rating: 3,
    matches: [
      { g: "-", a: "-" },
      { g: "-", a: "-" },
      { g: "-", a: "-" },
      { g: "-", a: "-" },
      { g: 1, a: 1 },
      { g: "-", a: "-" },
    ],
  },
  {
    name: "Carol (Daniboy)",
    rating: 1,
    matches: [
      { g: "-", a: "-" },
      { g: "-", a: "-" },
      { g: "-", a: "-" },
      { g: "-", a: "-" },
      { g: 0, a: 0 },
      { g: 0, a: 1 },
    ],
  },
  {
    name: "Berpai",
    rating: 4,
    matches: [
      { g: "-", a: "-" },
      { g: "-", a: "-" },
      { g: 1, a: 0 },
      { g: "-", a: "-" },
      { g: "-", a: "-" },
      { g: "-", a: "-" },
    ],
  },
];
